- README.md
Fixes #131
Removed Cacheable Template language
General clean up
> ReadMe Clean Up

- code/admin/ProductAdmin.php
- code/extensions/FoxyCartSiteConfig.php
- code/objects/OptionGroup.php
- code/objects/OptionItem.php
- code/pages/ProductPage.php
Updated other classes that referenced categeories and optiongroups.
OptionGroup clean up.
Fixes #154
> moved categories and optiongroups to Settings

- code/pages/ProductHolder.php
- code/pages/ProductPage.php
- css/foxycart.css
- javascript/product_init.js
- templates/Includes/FlexSlider.ss
- templates/Layout/OrderHistoryPage.ss
- templates/Layout/ProductHolder.ss
- templates/Layout/ProductPage.ss
> Requirements - remove from controller init, move to templates

- code/controllers/FoxyCart_Controller.php
- code/model/FoxyCart.php
- code/objects/Order.php
- code/objects/OrderAddress.php
- code/objects/OrderDetail.php
customer and product info
Fixes #146
Allows for guest checkout. OrderAddresses are associated with Order
> FoxyCart_Controller::handleDataFeed - work on parsing

- code/pages/ProductPage.php
- javascript/outOfStock.js
- templates/Layout/ProductPage.ss
> adding out of stock text for product options that aren't currently available.

- code/objects/OptionItem.php
- code/objects/ProductImage.php
- code/pages/ProductPage.php
Option Item - added Available as a summary field
ProductImage - added CMSThumbnail as summary field
> OptionItem, ProductImage Summary Fields

- code/objects/ProductCategory.php
Adjust data types for Title and Code
> Update ProductCategory to have indexed Code

- README.md
- docs/en/Features.MD
- docs/en/Use.MD
Created docs/en/Features.MD
Created docs/en/Use.md
ReadMe updates and formatting.
> ReadMe cleanup, created additional guides in docs/en

- code/pages/ProductPage.php
> Update ProductPage to allow for custom preview image description

- code/pages/ProductPage.php
- templates/Layout/ProductHolder.ss
- templates/Layout/ProductPage.ss
> Update ReceiptTitle to be HTMLVarchar for special chars

- code/objects/OptionItem.php
> Remove Category from OptionItem

- code/pages/ProductPage.php
- tests/ProductPageTest.php
> BUGFIX leading/trailing space in title breaks encryption

- code/pages/ProductPage.php
- templates/Layout/ProductPage.ss
Simplified CartScript (formally ColorBoxScript) call.
> CartScript cleanup

- javascript/outOfStock.js
> fixes out of stock check

- code/extensions/FoxyStripeSiteConfig.php
> add trailing slash to FoxyCart URLs

- javascript/outOfStock.js
> change where (out of stock) message is applied

- tests/ProductPageTest.php
> Update test to prevent 50/50 failure

- code/objects/ProductDiscountTier.php
- code/pages/ProductPage.php
- tests/FoxyStripeTest.yml
- tests/ProductDiscountTierTest.php
Bugfix submit button not encrypted
> Enhancement add bulk price percentage discount

- code/extensions/FoxyStripeSiteConfig.php
- code/objects/OptionItem.php
- code/objects/Order.php
- code/objects/ProductCategory.php
- code/objects/ProductImage.php
- code/pages/ProductHolder.php
- code/pages/ProductPage.php
fixes #111
Order, FoxyStripeSiteConfig , ProductPage, ProductHolder, ProductImage, ProductCategory, OptionItem
ProductHolder - removed PreviewImage (not used in base install)
> i18n work for CMSField translations

- code/admin/OrderAdmin.php
- code/objects/Order.php
Fixes #212
Customized OrderAdmin to remove edit button
> OrderAdmin Cleanup

- code/objects/OptionItem.php
> BUGFIX ProductOption not properly implemented

- code/extensions/FoxyStripeSiteConfig.php
- tests/StoreSettingsTest.php
fixes #217
generate StoreKey if empty or NULL
updated StoreSettingsTest to use requireDefaultRecords
> FoxyStripeSiteConfig - requireDefaultRecords

- code/pages/ProductPage.php
I'm open to discussion on how best to adjust this, but wanted to get something rolling as it's critical to get this fixed.
> BUGFIX unavailable product still shows add to cart

- css/foxycart.css
- templates/Layout/ProductHolder.ss
- templates/Layout/ProductPage.ss
use $ProductRating to show 5 star rating
use $ProductReviews to show reviews and review form
done in such a way that they should be ignored if foxystripe-reviews module is not installed.
required for reviews to be "drop in" with default templates
> Integrate variables for Product Reviews into default templates

- code/pages/ProductPage.php
> BUGFIX add to cart errors with no Store Name set

- code/form/FoxyStripeDropdownField.php
> Add FoxyStripeDropdownField

- docs/en/changelogs/1.1.0.md
- docs/en/changelogs/1.1.1.md
- docs/en/changelogs/1.1.2.md
- docs/en/changelogs/index.md
Update incorrect years in 1.1.0.md and 1.1.1.md
> Add 1.1.2 changelog

- .travis.yml
- composer.json
Update composer.json to allow for additional SS versions and to suggest additional modules rather than require.
> Update travis settings to test additional SS versions

- code/pages/ProductPage.php
prefix field name attr with h: to hide in cart, checkout and receipt
> hide product_id in FoxyCart receipt

- _config/config.yml
- code/extensions/FoxyStripePageExtension.php
- code/pages/ProductPage.php
- templates/Layout/ProductHolder.ss
adds getCartScript() to Page, makes $CartScript in template available to all pages in site.
> PageExtension - getCartScript

- code/pages/ProductHolder.php
with GridFieldRelationHandler and SortableGridField
> ProductHolder - fix GridField integration

- .travis.yml
- composer.json
> Composer update - SilverStripe 3.2

- .gitignore
- _config/config.yml
- code/extensions/FoxyStripeProductFormFieldExtension.php
- code/pages/DonationProduct.php
- javascript/donationProduct.js
textfield to enter price in ProductForm
> DonationProduct

- code/objects/OptionItem.php
> Option Item - allow `getAvailability()` to be extended

- code/controllers/FoxyStripe_Controller.php
Fixes bug - user created in FoxyCart, account created on website, salt being set to ‘’ onBeforeWrite in Member
> FoxyStripe_Controller - customer Salt fix

- _config/config.yml
- code/extensions/FoxyStripeSiteConfig.php
- code/model/FoxyStripeClient.php
- code/objects/ProductCategory.php
- composer.json
- phpunit.xml
- tests/FoxyStripeSiteConfigTest.php
- tests/ProductCategoryTest.php
focus on Store Settings, Advanced
ping #279
> FoxyCart Hyper API Integration - initial

- src/Admin/OrderAdmin.php
- src/Form/FoxyStripeDropdownField.php
- src/Form/FoxyStripePurchaseForm.php
- src/Model/OptionGroup.php
- src/Model/OptionItem.php
- src/Model/Order.php
- src/Model/OrderDetail.php
- src/Model/OrderOption.php
- src/Model/ProductImage.php
- src/Page/OrderHistoryPage.php
- src/Page/ProductPage.php
Added / fixed docs and minor things
> Fixed OrderAdmin erroring on load

- composer.json
- src/Model/FoxyCart.php
- src/Model/FoxyStripeClient.php
- src/Model/FoxyStripeSetting.php
> API - add is_valid check

- src/Model/OptionItem.php
> OptionItem - set Weight to Decimal

- _config/legacy.yml
> feature - legacy.yml for SilverStripe 4 upgrades

- src/Form/FoxyStripePurchaseForm.php
- src/Model/foxycart.cart_validation.php
added missing use statement in cart_validation
> PurchaseForm - Image->Pad()

- src/Controller/FoxyStripeController.php
> bugfix - update SSO redirect link to accommodate custom SSL

- src/Controller/FoxyStripeController.php
> Order processing

- src/Model/FoxyStripeSetting.php
- src/Model/OrderDetail.php
Added minor docs to order detail
> Fixed get_template_global_variables calling the wrong function

- src/Model/FoxyCart.php
- src/Model/FoxyStripeSetting.php
> enhancement - implement CustomSSL option in 4 brach

- src/Page/ProductPage.php
- also simplified title trimming
- removes possibility of cms users creating cart validation errors when adding a product to a cart on the front end
Fixes #354
> Added trimming to product code and receipt title

- composer.json
> Fixed missing sortable field dependency

- src/Controller/FoxyStripeController.php
- simplified some logic with finding or creating an order object
> Fixed order processing creating duplicate orders

- _config/routes.yml
- src/Controller/DataTestController.php
- templates/TestData.ss
- its easier to just include it in the module than to pass the same php file around
- loads route and store key instead of hardcoded
- route is only available in dev
> Added a controller to test the data feed

- src/Page/ProductPage.php
- templates/Dynamic/FoxyStripe/Includes/FlexSlider.ss
- updated the template
- updated php docs
> Added method for getting sorted images

- src/Form/FoxyStripePurchaseForm.php
- src/Page/ProductPage.php
fixes #317
Ensure Code is unique via index and validator
Move weight to Main tab due to being required
> FoxyStripePurchaseForm - only include Weight if greater than 0

- src/Model/FoxyCart.php
> bugfix - FoxyCart::getAPIRequest - allow for CustomSSL

- src/Page/ProductPage.php
> ProductPage - check if Controller::has_curr()

- _config/config.yml
- src/API/Client/CustomerClient.php
- src/Admin/FoxyStripeAdmin.php
- src/Controller/FoxyStripeController.php
- src/Foxy/Transaction.php
- src/Model/FoxyCart.php
- src/Model/FoxyStripeClient.php
- src/Model/FoxyStripeSetting.php
- src/Model/Order.php
- src/ORM/CustomerExtension.php
- src/Security/PasswordEncryptor_BCrypt.php
- tests/PasswordEncryptor_BCryptTest.php
This is a refactor to utilize the hyper media api to push customer data to Foxy. Post checkout data will still be processed with the existing methodology as the response is a xml data feed.
> BUGFIX single sign on issues

- composer.json
- src/Model/OptionGroup.php
- src/Model/OptionItem.php
UPDATE only allow product options to be added on Product Pages
> BUGFIX modifiers error in admin if no product is set
